export const NAVIGATION_CATEGORIES_ROUTE = 'NAVIGATION_CATEGORIES_ROUTE'
export const NAVIGATION_PRODUCTS_ROUTE = 'NAVIGATION_PRODUCTS_ROUTE';
export const NAVIGATION_PRODUCT_DETAILS_ROUTE = 'NAVIGATION_PRODUCT_DETAILS_ROUTE'
export const NAVIGATION_AUDIO_PLAYER = 'NAVIGATION_AUDIO_PLAYER'
export const NAVIGATION_HOME_ROUTE = 'NAVIGATION_HOME_ROUTE'
export const NAVIGATION_SIGNIN_ROUTE = 'NAVIGATION_SIGNIN_ROUTE'
export const NAVIGATION_PAWYALL_ROUTE = 'NAVIGATION_PAYWALL_ROUTE'